-- consulta 3
DECLARE
    v_medico_id NUMBER;
BEGIN
    FOR i IN 1..2 LOOP
        INSERT INTO MEDICO_ELABORADOR (CODIGO, CPF, CNPJ, CRM_NUMERO, CRM_ESTADO, NOME, ESPECIALIDADE, ENDERECO, TELEFONE, SALARIO, CARGA_HORARIA, DATA_ADMISSAO, DATA_DEMISSAO)
        VALUES (MEDICO_ELABORADOR_SEQ.NEXTVAL, '12345678901', '12345678901234', 'CRM12345', 'SP', 'Dr. João', 'Clínico Geral', 'Rua A', '1234567890', 5000.00, 40, TO_DATE('2024-04-14', 'YYYY-MM-DD'), NULL)
        RETURNING CODIGO INTO v_medico_id;

        FOR j IN 1..ROUND(DBMS_RANDOM.VALUE(0, 5)) LOOP
            INSERT INTO DEPENDENTE (CODIGO_DEPENDENTE, CODIGO_MEDICO_ELABORADOR, NOME, IDADE, SEXO)
            SELECT ROUND(DBMS_RANDOM.VALUE(1, 100)), v_medico_id, 'Dependente_' || j, ROUND(DBMS_RANDOM.VALUE(1, 10)), CASE ROUND(DBMS_RANDOM.VALUE(0, 1)) WHEN 0 THEN 'Masculino' ELSE 'Feminino' END
            FROM DUAL;
        END LOOP;
    END LOOP;
END;

-- consulta 10

DECLARE
    v_medico_id NUMBER;
    v_atendimento_id NUMBER;
    v_convenio_id NUMBER;
    v_cpf_paciente PACIENTE.CPF%TYPE;
BEGIN
    FOR i IN 1..5 LOOP -- Número de médicos a serem adicionados
        INSERT INTO MEDICO_REQUISITANTE (CODIGO, CPF, CNPJ, CRM_NUMERO, CRM_ESTADO, NOME, ESPECIALIDADE, END_RUA, END_BAIRRO, END_CIDADE, END_ESTADO, END_CEP)
        VALUES (MEDICO_REQUISITANTE_SEQ.NEXTVAL, 12343213 || i, 'CNPJ_Medico_' || i, 'CRM_Numero_' || i, 'CRM_Estado_' || i, 'Nome_Medico_' || i, 'Especialidade_' || i, 'Rua_' || i, 'Bairro_' || i, 'Cidade_' || i, 'Estado_' || i, 'CEP_' || i)
        RETURNING CODIGO INTO v_medico_id;

       -- Adicionando convenios aleatoriamente
        INSERT INTO CONVENIO (CODIGO_ANS, CODIGO_OPERADORA, CNPJ, NOME, ENDERECO, EMAIL)
        VALUES(CONVENIO_SEQ.NEXTVAL, '12345', '1234445', 'CONVENIO DOS SANTOS', 'RUA CONVENIO', 'CONVENIO@EMAIL.COM')
        RETURNING CODIGO_ANS INTO v_convenio_id;

        SELECT CODIGO_ANS INTO v_convenio_id FROM (SELECT CODIGO_ANS FROM CONVENIO ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;
        INSERT INTO CONVENIO_MEDICO_REQUISITANTE (CODIGO_ANS, CODIGO_MEDICO_REQUISITANTE) VALUES (v_convenio_id, v_medico_id);

        INSERT INTO PACIENTE (CPF, NOME, EMAIL, SEXO, DATA_NASCIMENTO, END_CEP, END_ESTADO, END_CIDADE, END_BAIRRO, END_NUMERO, END_RUA)
        VALUES (PACIENTE_SEQ.NEXTVAL || i, 'Nome_Paciente_' || i, 'Email_Paciente_' || i, 'F', SYSDATE, 'Cep_'|| i, 'Estado_' ||  i, 'Cidade_' || i, 'Bairro_' || i, 'Num_' || i, 'Rua_' || i)
        RETURNING CPF INTO v_cpf_paciente;

        SELECT SUBSTR(CPF, 1, 11) INTO v_cpf_paciente FROM (SELECT CPF FROM PACIENTE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM = 1;

        INSERT INTO ATENDIMENTO (CODIGO, CPF_PACIENTE, CODIGO_ANS, CODIGO_MEDICO_REQUISITANTE, DATA_ATENDIMENTO)
        VALUES (ATENDIMENTO_SEQ.NEXTVAL, v_cpf_paciente, v_convenio_id, v_medico_id, SYSTIMESTAMP)       
        RETURNING CODIGO INTO v_atendimento_id;
    END LOOP;
END;
