-- Consulta 1: Liste o nome dos convênios que cobrem todos os exames.
SELECT C.NOME
FROM CONVENIO C
WHERE NOT EXISTS (
    SELECT E.CODIGO
    FROM EXAME E
    WHERE NOT EXISTS (
        SELECT 1
        FROM EXAME_PROVIDO EP
        WHERE EP.CODIGO_ANS = C.CODIGO_ANS
        AND EP.CODIGO_EXAME = E.CODIGO
    )
);

-- Consulta 3: Liste o nome e o código dos médicos elaboradores e a quantidade de dependentes.
SELECT M.NOME, M.CODIGO, COUNT(D.CODIGO_DEPENDENTE) AS NUM_DEPENDENTES
FROM MEDICO_ELABORADOR M
LEFT JOIN DEPENDENTE D ON M.CODIGO = D.CODIGO_MEDICO_ELABORADOR
GROUP BY M.NOME, M.CODIGO

-- Consulta 5: Liste o código ans e o nome dos convênios que possuem atendimentos no mês 04/2024.

SELECT c.codigo_ans, c.nome
FROM atendimento atd
JOIN convenio c ON atd.codigo_ans = c.codigo_ans
WHERE EXTRACT(MONTH FROM atd.data_atendimento) = 4
  AND EXTRACT(YEAR FROM atd.data_atendimento) = 2024;

-- Consulta 6: Liste os médicos elaboradores com mais de 2 dependentes.
SELECT M.CODIGO, M.NOME, COUNT(D.CODIGO_DEPENDENTE) AS NUM_DEPENDENTES
FROM MEDICO_ELABORADOR M
LEFT JOIN DEPENDENTE D ON M.CODIGO = D.CODIGO_MEDICO_ELABORADOR
GROUP BY M.CODIGO, M.NOME
HAVING COUNT(D.CODIGO_DEPENDENTE) > 2;

-- Consulta 9: Mostre a quantidade de vezes que cada pagamento foi utilizado por mês.
SELECT 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY') AS MES_ANO,
    FP.FORMA AS FORMA_PAGAMENTO,
    COUNT(FPA.CODIGO_FORMA_PAGAMENTO) AS QUANTIDADE_UTILIZADA
FROM 
    ATENDIMENTO A
JOIN 
    FORMAS_PAGAMENTO_ATENDIMENTO FPA ON A.CODIGO = FPA.CODIGO_ATENDIMENTO
JOIN 
    FORMAS_PAGAMENTO FP ON FPA.CODIGO_FORMA_PAGAMENTO = FP.ID
GROUP BY 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY'),
    FP.FORMA
ORDER BY 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY'),
    QUANTIDADE_UTILIZADA DESC;

