-- Consulta 1: Liste o nome dos convênios que cobrem todos os exames.
SELECT C.NOME
FROM CONVENIO C
WHERE NOT EXISTS (
    SELECT E.CODIGO
    FROM EXAME E
    WHERE NOT EXISTS (
        SELECT 1
        FROM EXAME_PROVIDO EP
        WHERE EP.CODIGO_ANS = C.CODIGO_ANS
        AND EP.CODIGO_EXAME = E.CODIGO
    )
);

-- Consulta 9: Mostre a quantidade de vezes que cada pagamento foi utilizado por mês.
SELECT 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY') AS MES_ANO,
    FP.FORMA AS FORMA_PAGAMENTO,
    COUNT(FPA.CODIGO_FORMA_PAGAMENTO) AS QUANTIDADE_UTILIZADA
FROM 
    ATENDIMENTO A
JOIN 
    FORMAS_PAGAMENTO_ATENDIMENTO FPA ON A.CODIGO = FPA.CODIGO_ATENDIMENTO
JOIN 
    FORMAS_PAGAMENTO FP ON FPA.CODIGO_FORMA_PAGAMENTO = FP.ID
GROUP BY 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY'),
    FP.FORMA
ORDER BY 
    TO_CHAR(A.DATA_ATENDIMENTO, 'MM/YYYY'),
    QUANTIDADE_UTILIZADA DESC;

